package com.hdwbinfo.hdwebupa;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2022-07-10T00:19:38.636-04:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://www.HDWEBUPA.HDWBINFO.com", name = "HDWEBUPAPort")
@XmlSeeAlso({https.www_hdwebupa_hdwbinfo_request.ObjectFactory.class, https.www_hdwebupa_hdwbinfo_response.ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2022-07-10T00:19:38.636-04:00", comments = "Apache CXF 3.4.3")
public interface HDWEBUPAPort {

    @WebMethod(operationName = "HDWEBUPAOperation")
    @RequestWrapper(localName = "HDWEBUPAOperation", targetNamespace = "https://www.HDWEBUPA.HDWBINFO.Request.com", className = "https.www_hdwebupa_hdwbinfo_request.ProgramInterface")
    @ResponseWrapper(localName = "HDWEBUPAOperationResponse", targetNamespace = "https://www.HDWEBUPA.HDWBINFO.Response.com", className = "https.www_hdwebupa_hdwbinfo_response.ProgramInterface")
    @WebResult(name = "info_rec", targetNamespace = "https://www.HDWEBUPA.HDWBINFO.Response.com")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2022-07-10T00:19:38.636-04:00")
    public https.www_hdwebupa_hdwbinfo_response.ProgramInterface.InfoRec hdwebupaOperation(

        @WebParam(name = "info_rec", targetNamespace = "https://www.HDWEBUPA.HDWBINFO.Request.com")
        https.www_hdwebupa_hdwbinfo_request.ProgramInterface.InfoRec infoRec
    );
}
