insert into postgres.promo_rate
(
    id,
    promo_code,
    promo_description,
    rate_card,
    product_code,
    promo_start_date,
    promo_end_date,
    daily_rate1,
    sunday_rate1,
    cycle_cost1,
    promo_duration1,
    daily_rate2,
    sunday_rate2,
    cycle_cost2,
    promo_duration2,
    daily_rate3,
    sunday_rate3 ,
    cycle_cost3 ,
    promo_duration3,
    number_of_tiers,
    create_date,
    created_by)
values
    (
        2,
        'P297',
        'HD NO EXP',
        1,
        'DS',
        '2022-01-01',
        '2023-01-01',
        1.101,
        5.394,
        48,
        999,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        now(),
        'zina')

;