/*
 * Aristo Suspense Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nytimes.spg.suspendServer.server.api;

import com.nytimes.spg.suspendServer.server.ApiException;
import com.nytimes.spg.suspendServer.server.model.CreateTempSusupenseCommand;
import com.nytimes.spg.suspendServer.server.model.GetTempSusupenseResponse;
import com.nytimes.spg.suspendServer.server.model.SuspenseErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SuspendApi
 */
@Disabled
public class SuspendApiTest {

    private final SuspendApi api = new SuspendApi();

    /**
     * Create temp suspense txn
     *
     * Availability: * Internal: Yes * External: No * Core: Yes  Overview:  Create temporary suspence transactions Headers: For internal authentication use:     1. X-NYT-LDAP, X-NYT-CLIENT-ID, X-NYT-CLIENT-SECRET (The most preferable way)     2. X-NYT-LDAP, X-NYT-AUTHORIZATION For external authentication use:     1. COOKIE, X-NYT-SARTRE-TOKEN, CONTENT-TYPE 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTempSuspenceTest() throws ApiException {
        String accountId = null;
        CreateTempSusupenseCommand body = null;
        GetTempSusupenseResponse response = api.createTempSuspence(accountId, body);
        // TODO: test validations
    }

}
