/*
 * Aristo Suspense Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nytimes.spg.suspendServer.server.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateTempSuspenseResponseData
 */
public class CreateTempSuspenseResponseDataTest {
    private final CreateTempSuspenseResponseData model = new CreateTempSuspenseResponseData();

    /**
     * Model tests for CreateTempSuspenseResponseData
     */
    @Test
    public void testCreateTempSuspenseResponseData() {
        // TODO: test CreateTempSuspenseResponseData
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'suspenseReason'
     */
    @Test
    public void suspenseReasonTest() {
        // TODO: test suspenseReason
    }

    /**
     * Test the property 'donationFlag'
     */
    @Test
    public void donationFlagTest() {
        // TODO: test donationFlag
    }

    /**
     * Test the property 'suspenseStartDate'
     */
    @Test
    public void suspenseStartDateTest() {
        // TODO: test suspenseStartDate
    }

    /**
     * Test the property 'suspenseEndDate'
     */
    @Test
    public void suspenseEndDateTest() {
        // TODO: test suspenseEndDate
    }

}
